US24 Confirmation page added
coyjiv/ISOCIAL pull request #15
Opened 2024-01-20 19:30 UTC by ChernovAleksey

2024-01-21 13:35 UTC, akiselevych requested changes

2024-01-21 13:35 UTC, akiselevych commented on backend/src/main/resources/resources/assets/index-Hr009OrK.js
Тебе надо удалить из рерурсов джавы фронт, он не должен попадать на гит

2024-01-21 13:35 UTC, akiselevych commented on client/src/components/confirmation/Confirmation.jsx
> +        <h2>Something went wrong. We can't confirm Your account</h2>
Линтер на фронте ругается на апостроф, его надо заменить

2024-01-21 13:35 UTC, akiselevych commented on client/src/components/confirmation/Confirmation.jsx
Данил сказал, что не говорил, что будет сам прописывать стили, по этому надо стилизовать компоненткрасивенько, добавить какую то картинку

2024-01-22 07:18 UTC, akiselevych approved these changes

2024-01-23 14:18 UTC, coyjiv commented
@ChernovAleksey падает проверка бека, это уже не из-за меня, нужно исправить сперва
![image](https://github.com/coyjiv/ISOCIAL/assets/33584261/32896296-ce3f-479d-9832-64f025ca5125)

2024-01-23 16:26 UTC, merged