[US17] Create users's profile endpoints done
coyjiv/ISOCIAL pull request #20
Opened 2024-01-24 19:17 UTC by romasyk

2024-01-25 18:33 UTC, akiselevych requested changes

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/dto/respone/UserResponseDto.java
Треба більш явне ім'я для dto, тому що дто юзерів для респонсу буде не одне. + dateOfBirth додати треба

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/UserRestController.java
всі конвертації в дто потрібно робити в сервісі, так як це бізнес логіка і вона інкапсулюється в прошарку сервісів

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> +    Pageable pageable = (Pageable) PageRequest.of(page - 1, size, sort);
кастити в Pageable не треба, воно вже повертає об'єкт типу Pageable

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> +    Pageable pageable = (Pageable) PageRequest.of(page - 1, size, sort);
+ додати анотацію транзакції з рідонлі

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
метод updateUser нічого не робить, треба переробити

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
метод deleteUser видаляє без перевірки на те, хто надсилає реквест. але зараз не виправляй, в моїй гілці для цього є гарні методи вже, потім виправиш

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/UserRestController.java
+ у нас контроллери без вказання, що це рест контроллер, треба перейменувати, щоб дотримуватись однакових неймінгів

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/dao/UserRepository.java
робити два окремих методи під пошук не дуже добре, дивись ось квері яке одним разом зробить те, що у тебе в двох методах, і поверне не Page,а  одразу ліст але з пагінацією

  @Query("SELECT u FROM User u WHERE u.firstName LIKE %:searchTerm% OR u.lastName LIKE %:searchTerm")
  List<User> findByFullName(@Param("searchTerm") String searchTerm,Pageable pageable);

2024-01-25 18:33 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> +    Pageable pageable = (Pageable) PageRequest.of(page - 1, size, sort);
+ залишив що до цього блоку коду коментарій в юзер репозиторії, треба покращити логіку змінивши два квері в одне

2024-01-25 18:34 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/dao/UserRepository.java
якщо що то пиши мені я допоможу тобі це зробити

2024-01-26 16:03 UTC, coyjiv commented on backend/src/main/java/com/coyjiv/isocial/dto/respone/UserResponseDto.java
@akiselevych  Може ProfileResponseDto?

2024-01-26 22:11 UTC, akiselevych requested changes

2024-01-26 22:11 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/UserRestController.java
кажу ж, що всі дто потрібно конвертити в сервісі) усю логіку з конверт в дто треба інкапсулювати там

2024-01-26 22:11 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> +        return userRepository.findById(id);
треба щоб повертало тільки активного

2024-01-26 22:11 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> +        return userRepository.findByName(names[0], pageable);
а чому page - 1 ? 
і ще не дуже зрозумів чого ми передаєм тільки 1 частину ім'я яке шукаємо, у нас же квері оновлена працює навіть якщо ім'я + прізвище вводити ?

2024-01-26 22:11 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/UserRestController.java
і перейменувати на UserController

2024-01-26 22:11 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/UserRestController.java
і ще там чек стайл не пропускає коміт

2024-01-27 17:22 UTC, akiselevych approved these changes

2024-01-27 17:57 UTC, merged