Us25
coyjiv/ISOCIAL pull request #27
Opened 2024-02-01 09:48 UTC by 1Andriy

2024-02-02 16:03 UTC, coyjiv commented
Падают экшены, проверяй ошибки перед коммитом, используя mvn validate @1Andriy 
Нет смысла ревьювить если смержить нельзя

2024-02-02 21:12 UTC, akiselevych requested changes
Написав усі пункти в тг

2024-02-06 19:30 UTC, akiselevych requested changes
якшо зараз в sendFriendRequest передати неіснуючий ід юзера то програма не обробить цей випадок і викине 500 помилку
і в declineFriendRequest ти викадєш IllegalStateException, але то э RuntimeException і вона unchecked, заміни краще на IllegalAccessException, шоб її програма могла відловити

2024-02-09 20:43 UTC, ghost reviewed
Good

2024-02-09 20:43 UTC, akiselevych reviewed
Good

2024-02-09 20:44 UTC, ghost approved these changes

2024-02-09 20:44 UTC, merged