[US30] Create endpoint favorite posts
coyjiv/ISOCIAL pull request #32
Opened 2024-02-06 20:14 UTC by ChernovAleksey

2024-02-07 19:47 UTC, akiselevych requested changes
Посмотрел, все работает, только когда пост удаляется, то фаворит остается активным.
Вот это пофиксить и можно мержить

2024-02-09 20:59 UTC, akiselevych requested changes
500 ошибка когда удаляется пост на котором есть фавориты

2024-02-13 06:57 UTC, akiselevych requested changes
Все отлично, работает. Осталось только изменить ДТО, что бы на фронт после гет запросов приходили данные поста, что бы с фронта лишний раз не делать на другой ресурс запрос

2024-02-17 13:14 UTC, akiselevych submitted a review, later dismissed

2024-02-17 13:14 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/transfer/user/UserDefaultResponseMapper.java
> +    dto.setPremiumEmoji( entity.isPremium() ? entity.getPremiumEmoji() : null);
Тебе не надо в декорейт засовывать поля с оданаковыми названиями, декорейт ентети надо если у тебя как то бизнес логика мапинга полей, а чисто копировать с поля в поле оно само сможет

2024-02-17 13:14 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/transfer/user/UserUpdateRequestMapper.java
> +
тут тоже самое

2024-02-18 23:47 UTC, coyjiv approved these changes

2024-02-18 23:48 UTC, merged