Us15
coyjiv/ISOCIAL pull request #37
Opened 2024-02-15 17:02 UTC by 1Andriy

2024-02-17 12:40 UTC, akiselevych requested changes, later dismissed
Фінально, що треба переробити:

1) В дто отримуати тільки пароль, а uuid приймати в контролері як квері параметр. 
2) Перевіряти, якщо хтось намагається зареквестити скидування паролю на неіснуючу пошту, видавати помилку.
3) прибрати .requestMatchers(mvcMatcherBuilder.pattern("/api/users/**")).permitAll()

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/configs/auth/SecurityConfig.java
> +                            .requestMatchers(mvcMatcherBuilder.pattern("/api/users/**")).permitAll()
???, це не потрібно відкривати для всіх

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/rest/UserController.java
> +  @PostMapping("/reset-password")
Резет пасворд в auth контролері треба

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/rest/UserController.java
> +  public ResponseEntity<?> resetPassword(@RequestParam String email, @RequestParam String newPassword) {
Новий пароль не треба параметром приймати, створи дто де буде поле новий пароль, це більш безпечніше

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/resource/rest/AuthenticationController.java
> +  @PostMapping("/reset-password")
Бачу, що переніс, гуд

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/dto/request/auth/PasswordResetRequestDto.java
> +  private String uuid;
Але тобі не потрібно приймати в дто uuid, це ж частина посилання ..

2024-02-17 12:40 UTC, akiselevych commented on backend/src/main/java/com/coyjiv/isocial/service/user/UserService.java
> -
Чого прибрав? Навпаки якщо користувач намагається відновити пароль на не існуючій пошті, треба давати помилку

2024-02-19 00:15 UTC, coyjiv commented on backend/src/main/java/com/coyjiv/isocial/service/email/EmailServiceImpl.java
> +    String resetUrl = "http://localhost:9000/forgotPassword?id=UUID" + uuid;
hardcoded values are bad

2024-02-19 00:52 UTC, coyjiv approved these changes

2024-02-19 00:53 UTC, merged